### ISSUE TITLE
While editing the post, image does not appear automatically! Need to sort out which image 

### ISSUE THREAD

**Issue by akanseitzhanov** [karnurmax/knm-portal#10]
Посттарды озгерткенде? букил данныйлар до этого тандалган сразу шыгады, бирак кай сурет екендиги шыкпайды

**Comment by karnurmax** [comment]
суреттер сақталатын жер қайда ? сақтаған кезде path базада да сақталады ма ?

**Comment by akanseitzhanov** [comment]
суреттер сакталады storage fileda, названиесы базада сакталады гой

**Comment by akanseitzhanov** [comment]
Жасалды и сизге корсетилген
