### ISSUE TITLE
While editing with Admin the author's post, the name changes from author to admin

### ISSUE THREAD

**Issue by akanseitzhanov** [karnurmax/knm-portal#4]
While editing with Admin the author's post, the name changes from author to admin

Quite difficult to solve....

**Comment by karnurmax** [comment]
триггер неде ? админ сақтаған кезде ғой. сол жерден бастап қазу керек, демек
кодта сол поле бойынша тауып алып көріңізші

**Comment by akanseitzhanov** [comment]
Solved , committed and pushed in akan_creating_plugin_options_branch
